[project]
name = "kioto"
version = "2.3.0"
description = "Standard library for Mire — core types, collections, I/O, networking, and more"
entry = "code/mod.mire"

[paths]
sources = "code"
tests = "tests"

[exports]
strings = "core/strings"
lists   = "core/lists"
dicts   = "core/dicts"
time    = "core/time"
fs      = "core/fs"
env     = "core/env"
proc    = "core/proc"
async   = "core/async"
mem     = "core/mem"
cpu     = "core/cpu"
gpu     = "core/gpu"
term    = "core/term"
math    = "core/math"
types   = "ext/types"
maybe   = "ext/maybe"
result  = "ext/result"
tuple   = "ext/tuple"
iter    = "ext/iter"
net     = "core/net"
log     = "core/log"
cli     = "core/cli"
json    = "ext/json"
ws      = "ext/ws"
crypto  = "core/crypto"
