[project]
name = "kioto"
version = "3.11.10"
entry = "mod.mire"

[exports]
strings = "core/strings"
lists   = "core/lists"
dicts   = "core/dicts"
time    = "core/time"
fs      = "core/fs"
env     = "core/env"
proc    = "core/proc"
async   = "core/async"
mem     = "core/mem"
cpu     = "core/cpu"
gpu     = "core/gpu"
term    = "core/term"
math    = "core/math"
types   = "ext/types"
maybe   = "ext/maybe"
result  = "ext/result"
tuple   = "ext/tuple"
iter    = "ext/iter"
