schema_version = "1.0"

[packages.kioto]
description = "Standard library for Mire — core types, collections, I/O, networking, and more"
version = "2.3.2"
path = "kioto"

[packages.sdl]
description = "SDL bindings for Mire — SDL2 and SDL3, split by functional area"
version = "1.0.1"
path = "sdl"
